<Project>
  <PropertyGroup>
    <CmuxAppVersion>0.1.6.7</CmuxAppVersion>
    <Version>$(CmuxAppVersion)</Version>
    <AssemblyVersion>$(CmuxAppVersion)</AssemblyVersion>
    <FileVersion>$(CmuxAppVersion)</FileVersion>
    <InformationalVersion>$(CmuxAppVersion)</InformationalVersion>
  </PropertyGroup>
</Project>
